### ISSUE TITLE
Customizable bottom nav bar buttons on mobile

### ISSUE THREAD

**Issue by shuuji3** [elk-zone/elk#2757]
This is the task tracking issue to resolve #641.

The goal of this new feature is to allow users to select their preferred buttons in the bottom nav bar on mobile view. The original issue proposed to move the three-dot button somewhere but that's out of scope and this will focus on the button selection/ordering.

## ToDo

- [x]  Extract the bottom nav buttons into independent components 
- [x]  Implement a settings page to arrange the order of the buttons 
- [ ]  ~~Add other types of buttons for the selection~~ postpone to a future PR
